spring:
  application:
    name: railway-notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:${HOME}/Sites/railways/railway-backend/railway-secrets/notification-secrets/notification-${spring.profiles.active}.properties

server:
  port: 8082
